services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: my-laravel13-app
    env_file:
      - .env
    entrypoint: ["/bin/bash", "/var/www/html/start.sh"]
    ports:
      - "${APP_PORT:-8888}:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    env_file:
      - .env
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${FORWARD_DB_PORT:-3307}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
